export const Colors = {
  PrimaryColor: 'primary-color',
  PrimaryColorDarker: 'primary-color-darker',
  PrimaryColorDark: 'primary-color-dark',
  PrimaryColorLight: 'primary-color-light',
  PrimaryColorLighter: 'primary-color-lighter',
  NeutralColor: 'neutral-color',
  NeutralColorDarker: 'neutral-color-darker',
  NeutralColorDark: 'neutral-color-dark',
  NeutralColorLight: 'neutral-color-light',
  NeutralColorLighter: 'neutral-color-lighter',
  SuccessColor: 'success-color',
  SuccessColorDarker: 'success-color-darker',
  SuccessColorDark: 'success-color-dark',
  SuccessColorLight: 'success-color-light',
  SuccessColorLighter: 'success-color-lighter',
  WarningColor: 'warning-color',
  WarningColorDarker: 'warning-color-darker',
  WarningColorDark: 'warning-color-dark',
  WarningColorLight: 'warning-color-light',
  WarningColorLighter: 'warning-color-lighter',
  DangerColor: 'danger-color',
  DangerColorDarker: 'danger-color-darker',
  DangerColorDark: 'danger-color-dark',
  DangerColorLight: 'danger-color-light',
  DangerColorLighter: 'danger-color-lighter',
  White: 'white',
} as const;

export type ColorsType = (typeof Colors)[keyof typeof Colors];
